language: python
python:
  - "3.6"

before_install:
  - mkdir ~/Music
  - sudo apt-get update
  - sudo apt-get install -y gvfs gvfs-backends gvfs-bin gvfs-common gvfs-daemons gvfs-fuse gvfs-libs

install:
  - pip install coveralls

script:
  - python setup.py test
  - coverage run -m unittest discover
  - coverage report -m --include=pysyncdroid*
  - bash tests/test_cli.sh

after_success:
  - coveralls

notifications:
  email: false
