language: python
python:
  - "3.6"

before_install:
  - mkdir ~/Music
  - sudo apt-get update
  - sudo apt-get install -y gvfs gvfs-backends gvfs-bin gvfs-common gvfs-daemons gvfs-fuse gvfs-libs

script:
  - python setup.py test

notifications:
  email: false
